# Generated by Django 5.1.1 on 2024-11-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='insession',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='uid',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterModelTable(
            name='roommember',
            table='memberMeeting',
        ),
    ]
