# Generated by Django 5.1.1 on 2024-11-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
