# Generated by Django 5.1.1 on 2024-11-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_event_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAssigned', models.DateField()),
                ('dueDate', models.DateTimeField()),
                ('taskDescription', models.TextField(max_length=255)),
            ],
        ),
    ]
