# Generated by Django 5.1.1 on 2024-11-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
