# Generated by Django 5.1.1 on 2024-11-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_task_assignto'),
        ('register_app', '0004_alter_members_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.members'),
        ),
    ]
