# Generated by Django 5.1.1 on 2024-11-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_alter_task_assignto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
    ]
