# Generated by Django 5.1.1 on 2024-11-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('meeting_title', models.CharField(max_length=100)),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
