# Generated by Django 5.1.1 on 2024-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0002_alter_members_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
