# Generated by Django 5.1.1 on 2024-11-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0003_alter_members_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_picture.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
